# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'AXyqC3Fx4iuuDyu0b5LOtY9CK'
  twitter_api_secret: 'd9VaQCptDIPoN1tC8jnNoEsOiwe9TBCxzFR9FXmwt3xb60CYdT'

development:
  secret_key_base: fed635d03db7845d20e10dba4ec7c336e4586152957a8117a4a6a4cc720a314f4584b591df7fbd49060b28ceae03657fb2bf0abc52c20952f94c89da2c5e882f
  <<: *default_twitter

test:
  secret_key_base: 28e5aaa407b8730ac08d6874cdd965931861c830145baaf93f1512ee0f19e918f355d92c2d74529e60d22cddcab03de6e7d553b966b5df7b6bd25b869188752f
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
